### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by alanhdu**
Set up `py.test` unittesting. 

A couple of questions:
- Is the `events.json` good, or is there a better way to do this? The problem with having a database is that the `/events/` endpoint gets all requests for _this_ week, so the datetimes need to change. With time, we might want to make a `users.json` too, but we can save that for later.
- Should tests have hardcoded ids (a la `test_search`), or should we use sqlalchemy queries instead?

### CODE REVIEW

**Comment by natebrennand** [comment]
Why `pytest` over `unittest`? Mitshuko seems to endorse just using `unittest`, presumably since it's standard library.

---

re: time dependent tests:
- you can mask the time of the entire process w/ [faketime](http://davidjb.com/blog/2010/07/linux-make-time-with-faketime/)
- you can monkey patch a python method call w/ [freezegun](http://stevepulec.com/freezegun/)

---

re: test data

a JSON file is fine.
I trend towards hardcoding the data since that's usually a noisier indicator of something being changed that shouldn't have been altered.

**Comment by alanhdu** [comment]
I'm used to`pytest`, so I decided to go with that. I know it also has pretty good hooks for [non-Python tests](https://pytest.org/latest/example/nonpython.html), which we might use for React testing.

---

Thanks for the references. I think what we're doing now is alright, but I'll definitely keep them in mind.

---

Hard-coded test results.

**Comment by alanhdu** [comment]
Will merge this soon, if no objections. I'll save react tests for another PR.

**Comment by alanhdu** [comment]
Merging.

**Pull request merged**
