### PR TITLE
add travis CI integration

### PR DESCRIPTION
**Pull request by natebrennand**
Adds a travis-CI configuration file to check pep8 compliance
Everything was already compliant, nice job!

### CODE REVIEW

**Comment by davidhao3300** [comment]
So once we add Travis, do we have to configure the repo to work with Travis?

**Comment by davidhao3300** [comment]
Addresses #54

**Comment by natebrennand** [comment]
You just need to enable it through travis-ci.org.
I've gone ahead and already done this, it should start running builds once it's merged

**Comment by davidhao3300** [comment]
:+1:

**Pull request merged**
